### ISSUE TITLE
implement "ease" in line_follow.py

### ISSUE THREAD

**Issue by mcodd** [cpb-gh/fll#19]
right now this is unimplemented with a couple lines about it commented out, but it does change from Sspeed to Espeed linearly based on https://github.com/cpb-gh/fll/blob/main/functions/line_follow.py#L31

**Comment by cpb-gh** [comment]
i am closing this put and removing the commented out easing stuff because i don't think we want easing in this function because this function has PID stuff that messes with the motor and there is no good way that i see to implement easing.
